import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./ui/Navbar";
import { SessionProvider } from "./context/SessionProvider";
import Footer from "./ui/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Blogging Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <SessionProvider>
        {/* <Navbar/>  */}
        {children}
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
